name: CI/CD Modulo Notificaciones

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del Código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Configurar Credenciales de AWS
      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          echo "Configuring AWS credentials..."
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "aws_session_token=${AWS_SESSION_TOKEN}" >> ~/.aws/credentials

      # 4. Instalar Dependencias
      - name: Install dependencies
        run: npm install

      # 5. Construir y Publicar la Imagen Docker
      - name: Build and push Docker image
        env:
          ECR_URI_NOTIFICACIONES: ${{ secrets.ECR_URI_NOTIFICACIONES }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          echo "Building Docker image for modulo-notificaciones"

          # Build Docker image with environment variables
          docker build --build-arg DB_HOST=$DB_HOST \
                       --build-arg DB_USER=$DB_USER \
                       --build-arg DB_PASSWORD=$DB_PASSWORD \
                       --build-arg DB_NAME=examen2 \
                       --build-arg SNS_TOPIC_ARN=$SNS_TOPIC_ARN \
                       -t modulo-notificaciones .

          # Log in to AWS ECR
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI_NOTIFICACIONES

          # Tag and push Docker image
          docker tag modulo-notificaciones:latest $ECR_URI_NOTIFICACIONES:modulo-notificaciones
          docker push $ECR_URI_NOTIFICACIONES:modulo-notificaciones
